language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
#  - "3.0"
#  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
install:
  - pip install coveralls
script:
  - make -C tools/python test
  - if [ "$TRAVIS_PYTHON_VERSION" = "2.7" ]; then cd python && coverage run --source=phonenumbers ./testwrapper.py && coverage report -m && cd ..; fi
after_success:
  - cd python && coveralls && cd ..
